version: '3'
networks:
   backend:
services:
   restheart:
      image: softinstigate/restheart
      container_name: restheart
      depends_on:
         - mongodb
      networks:
         - backend
      ports:
         - "8080:8080"
      # volumes:
      #   - ./etc:/opt/restheart/etc:ro

   mongodb:
      image: mongo:3.6
      container_name: restheart-mongo
      environment:
            MONGO_INITDB_ROOT_USERNAME: restheart
            MONGO_INITDB_ROOT_PASSWORD: R3ste4rt!
      command: --bind_ip_all --auth
      volumes:
         - ./data:/data/db
      networks:
         - backend
      ports:
        - "27017:27017"
